server:
  port: 8082
spring:
  profiles:
    active: dev
  application:
    name: vtm_comment
  cloud:
    nacos:
      server-addr: http://119.91.200.72:8848
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://119.91.200.72:3306/vtmer_interface_management?characterEncoding=UTF-8&useSSL=false
    username: root
    password: vtmer2020
logging:
  level:
    root: info
    com.tzy: debug
management:
  endpoints:
    web:
      exposure:
        include: "*"